### ISSUE TITLE
Variable Length Cypher Query over all Relationship Types

### ISSUE THREAD

**Issue by stevemarin** [memgraph/mgclient#30]
Hello!  Thank you VERY much for the great tool and, especially, for all the great docs & examples!

I'm trying to perform a query like:

`MATCH p=(from)-[rel *1..3]->(to) WHERE from.name = "Bob" AND to.name = "Frank" RETURN p`

I.e. All paths of length `1..3` from "Bob" to "Frank" regardless of the relation type.  I see how to do a variable length query with certain relationships, but not with all.  Am I missing something in the docs?  I have all the relationship types, so I could just build a string (`:FRIENDS_WITH:RELATED_TO:DATED`) and add the `*1..3` at the end.  But I just want to see if I'm missing something before I add that complexity.  THANK YOU!

**Comment by stevemarin** [comment]
Sorry, it's working.  My problem was using a `WHERE` clause to filter results based on relation properties.  My relations have dates, and I'm trying to filter such that I get all results between two dates.  I'm seeing the issue:

`DatabaseError: Only nodes, edges and maps have properties to be looked-up.`

How would I filter edges with dates as properties?

**Comment by stevemarin** [comment]
Again, sorry.  This should probably be on the discussion board.  Closing.

**Comment by gitbuda** [comment]
Hi! Thank you for your kind words! You can also use filter lambda with any variable length path expression, an example is here https://docs.memgraph.com/memgraph/reference-guide/graph-algorithms#breadth-first-search :D Memgraph actually doesn't support time data types yet, you have to use integer or string for the time representation at this point. But, the next release in the middle of September is going to have temporal types supported. Stay tuned for that :D

**Comment by MasterMedo** [comment]
Also, instead of using the `where` clause you can specify the attributes withing the `match` clause:

`MATCH p=(from {name: "Bob"})-[rel *1..3]->(to {name: "Frank"}) RETURN p`
