### ISSUE TITLE
mg_client_version returns 1.7.1 even if 1.7.3

### ISSUE THREAD

**Issue by toge** [memgraph/mgclient#67]
I read the policy about minor version in the comments.
Is there some policy about when mg_client_version should be upgraded?

```
project(mgclient VERSION 1.4.1)
...
add_definitions(-DMGCLIENT_VERSION="${mgclient_VERSION}")
```
https://github.com/memgraph/mgclient/blob/master/CMakeLists.txt#L22-L27

**Comment by gitbuda** [comment]
@toge you right 😃 That was a mistake on my side -> will take a look at how to best bump the version in the following days or on the next release 👀

**Comment by toge** [comment]
@gitbuda 
Thanks!
